spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  jwt:
    token:
      access:
        name: ${JWT_ACCESS_NAME}
        secret-key: ${JWT_ACCESS_KEY}
        expiration: ${JWT_ACCESS_EXPIRATION}  # (단위: 초 / 현재 1시간)
      refresh:
        name: ${JWT_REFRESH_NAME}
        secret-key: ${JWT_REFRESH_KEY}
        expiration: ${JWT_REFRESH_EXPIRATION}  # (단위: 초 / 현재 2주)

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${OAUTH_CLIENT_ID}
            client-secret: ${OAUTH_CLIENT_SECRET}
            scope: user:email, repo, contents, metadata

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

management:
  endpoints:
    web:
      base-path: /actuator  # actuator 기본 경로 설정
      exposure:
        include: health,info  # 노출할 엔드포인트
  endpoint:
    health:
      show-details: always  # 상세 정보 표시
      probes:
        enabled: true  # k8s 프로브 활성화
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true