version: "1"
services:
  redis-service:
    image: redis
    command: redis-server --port 6379
    container_name: scv-redis
    labels:
      - "name=scv-fast-redis"
      - "mode=standalone"
    ports:
      - 6380:6379
