datasets:
  MNIST:
    input_shape: [1, 28, 28]
    num_classes: 10
    mean: [0.1307]
    std: [0.3081]

  FASHION_MNIST:
    input_shape: [1, 28, 28]
    num_classes: 10
    mean: [0.2860]
    std: [0.3530]

  CIFAR10:
    input_shape: [3, 32, 32]
    num_classes: 10
    mean: [0.4914, 0.4822, 0.4465]
    std: [0.2470, 0.2435, 0.2616]
    augmentation: true

  SVHN:
    input_shape: [3, 32, 32]
    num_classes: 10
    mean: [0.4377, 0.4438, 0.4728]
    std: [0.1980, 0.2010, 0.1970]

  EMNIST:
    input_shape: [1, 28, 28]
    num_classes: 26
    mean: [0.1751]
    std: [0.3332]

  # 차후 추가