version: "3.5"

services:
  scv-search:
    image: a107scv/scv-model-search
    container_name: scv-model-search
    ports:
      - "8001:8001"
    environment:
      API_KEY: ${API_KEY}
      DB_NAME: ${DB_NAME}
      COLLECTION_NAME: ${COLLECTION_NAME}
      REDIS_HOST_NAME: ${REDIS_HOST_NAME}
      REDIS_PORT: ${REDIS_PORT}
    networks:
      - scv-search-network
  redis-service:
    image: redis
    command:
      [
        "redis-server",
        "--port",
        "6379",
        "--bind",
        "0.0.0.0",
        "--protected-mode",
        "no",
      ]
    labels:
      - "name=scv-fast-redis"
      - "mode=standalone"
    ports:
      - 6379:6379
    networks:
      - scv-search-network
networks:
  scv-search-network:
