version: "3.8"

services:
  minio:
    image: minio/minio
    container_name: scv-minio
    ports:
      - "9002:9000"
      - "9003:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_VOLUMES=/data
    volumes:
      - ${VOLUME_PATH}:/data # 원하는 경로로 수정하세요
      - ${CONFIG_DIR}:/etc # 환경 변수 파일 경로로 수정하세요
    command: server --console-address ":9001"
